let ron = Expert()
world.place(ron, facing: south, atColumn: 1, row: 5)
ron.collectGem()
ron.turnLockDown()
ron.turnLeft()
ron.move(distance: 3)
ron.collectGem()
ron.moveForward()
ron.collectGem()
ron.turnLockUp()
ron.turnRight()
ron.moveForward()
ron.collectGem()
ron.move(distance: 2)
ron.collectGem()
ron.moveForward()
ron.collectGem()
ron.turnLeft()
ron.turnLeft()
ron.move(distance: 4)
ron.turnLeft()
ron.move(distance: 4)
ron.turnRight()
for i in 1 ... 3 {
    ron.moveForward()
    ron.collectGem()
}


// CODE REVIEW BY DADDY: WELL DONE! :)
