let expert = Expert()

expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.turnLockUp()

expert.turnLeft() 
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()

expert.turnLeft() 
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()

expert.turnLeft() 
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.turnLeft()
expert.moveForward()
expert.moveForward()
expert.moveForward()
expert.collectGem()
